server:
  port: 11000

spring:
  application:
    name: rabbitmq
#  rabbitmq:
#    host: kanepan19.asuscomm.com
#    port: 15673
#    username: guest
#    password: guest
#    virtual-host: /
  cloud:
    stream:
      binders:
        output:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: kanepan19.asuscomm.com
                port: 15673
                username: guest
                password: guest
                virtual-host: GHost
        input:
          type: rabbit
          defaultCandidate: false
          environment:
            spring:
              rabbitmq:
                host: kanepan19.asuscomm.com
                port: 15673
                username: guest
                password: guest
                virtual-host: /
      bindings:
        output:
          binder: rabbit
          destination: order
          producer:
            autoStartup: true
        input:
          binder: rabbit
          destination: order
          producer:
            autoStartup: true
