server:
  port: 11004

spring:
  application:
    name: rocketmq-produce
  cloud:
    stream:
      rocketmq:
        binder:
          # RocketMQ 服务地址
          name-server: kanepan19.asuscomm.com:9876
        bindings:
          output:
            producer:
              group: produce-group
              async: true
          output2:
            producer:
              group: test-group2
              async: true
      bindings:
        output:
          destination: test-topic
          content-type: application/json

logging:
  level:
    org:
      springframework:
        cloud:
          stream:
            binder:
              rocketmq: DEBUG
